<br><br>

# Numpy

In [1]:
import numpy as np

#Creamos un np array de rango 1, 
un_array = np.array([7, 77, 777, 1234]) 
print(type(un_array))

<class 'numpy.ndarray'>


In [2]:
#imprimimos la forma (shape) del array
print(type(un_array.shape))

print(un_array.shape)

print(un_array)


<class 'tuple'>
(4,)
[   7   77  777 1234]


In [3]:
#accedemos a las variables
print(un_array[0])
print(un_array[1])
print(un_array[2])
un_array[2] = 4
print(un_array[2])

7
77
777
4


<br><br>

## Cómo crear un array multidimensional

In [4]:
otro = np.array([[ [11,12,13],  [22,23,24],  [22,23,24],  [22,23,24] ] , [ [11,12,13],  [22,23,24],  [22,23,24],  [22,23,24] ] ]) 
print("La forma de este array es: ",otro.shape)

La forma de este array es:  (2, 4, 3)


In [7]:
print("Así accedo a un valor de este array de dos dimensiones", otro[1,1])
print("Así imprimo el array completo")
print(otro)


Así accedo a un valor de este array de dos dimensiones [22 23 24]
Así imprimo el array completo
[[[11 12 13]
  [22 23 24]
  [22 23 24]
  [22 23 24]]

 [[11 12 13]
  [22 23 24]
  [22 23 24]
  [22 23 24]]]


$ I^{n \times n} =
\left( \begin{array}{cccc}
 11 & 12 & 13  \\ 
 22 & 23 & 24  \\ 
 35 & 36 & 37  \\ 
\end{array} \right) $


<br><br>

## Distintas maneras de crear nd arrays


In [21]:
#crear array lleno de ceros
ej1 = np.zeros((1080,1920,3))
print(ej1)


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [12]:
#creamos un array lleno de un valor determinado (floats por ejemplo)
ej2 = np.full((2,2), 9.1)
print(ej2)

[[9.1 9.1]
 [9.1 9.1]]


In [13]:
#creando un array de 2x2 condiagonal en "unos" y el resto cero
ej3 = np.eye(7,7)
print(ej3)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [17]:
#creando un array de "unos"
ej4 = np.ones((10,7))
print(ej4)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [20]:
# creamos un array de flotantes aleatorios entre 0 y 1
ej5 = np.random.random((5,5))
print(ej5)

[[0.74213461 0.08288792 0.24892635 0.43621459 0.08407122]
 [0.42076125 0.76014685 0.06966808 0.75014513 0.19513428]
 [0.49229742 0.29708461 0.21638062 0.56233836 0.96283426]
 [0.76459308 0.33442393 0.47221114 0.25307176 0.76838658]
 [0.785185   0.4841967  0.48333002 0.44171426 0.55376878]]



<br><br>

## Rebanando arrays (Slice)
Hacer Slice a un array, sirve para aislar una "sub-región" de la matriz de un ndarray

In [3]:
un_array = np.array([[11,12,13,14,15,16], [21,22,23,24,25,26], [31,32,33,34,35,36],[41,42,43,44,45,46]])
print(un_array)

[[11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]
 [41 42 43 44 45 46]]


In [4]:
#crearemos un slice de 2 x 2 a partir de "un_array"
un_slice = un_array[:2,1:3]
print(un_slice)

[[12 13]
 [22 23]]


In [5]:
#imprimimos el valor fila 0 columna 0 del slice
#como vemos en la salida, el slice genera un nuevo índice
print("Slice:", un_slice[0, 0]) 


Slice: 12


In [6]:
#ahora sumaremos 100 al valor de la posicion (0,0) del slice
#como veremos pudremos sumar sin problema alguno.
un_slice[0,0] += 100
print("Slice:", un_slice[0, 0]) 

Slice: 112


In [7]:
#hora imprimamos la posición (0,1) del array original, 
print("Array original:", un_array[0, 1]) 

Array original: 112


¿cómo, pero si al array original no lo tocamos?

In [9]:
#como confirmaremos aquí, un slice, no es más que un puntero o acceso directo al array original,\
# y si modificamos el slice en realidad estaremos modificando el array original.
print(un_array)
type(un_slice)

[[ 11 112  13  14  15  16]
 [ 21  22  23  24  25  26]
 [ 31  32  33  34  35  36]
 [ 41  42  43  44  45  46]]


numpy.ndarray

<br><br><b>Muy IMPORTANTE</b> <br>
Y si necesitáramos tener un nuevo array a partir de un slice?

In [10]:
nuevo_array = np.array(un_slice)
print(nuevo_array)


[[112  13]
 [ 22  23]]


In [ ]:
#volvamos al slice
#puedo seleccionar  una sola fila, entonces el slice será unidimensional.
row_rank1 = un_array[1, :]    
print(row_rank1, row_rank1.shape)  

In [ ]:
#lo mimso podemos hacer con una columna
row_rank1 = un_array[:, 1]    
print(row_rank1, row_rank1.shape)  

<br><br>
## Array de índices
A veces es útil, preparar una serie de índices en un array, para luego utilizarlos para operar sobre otro.

In [22]:
#creamos un nuevo array
array_a = np.array([[11,12,13], [21,22,23], [31,32,33], [41,42,43]])
print(array_a)
print(array_a.shape)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]
(4, 3)


In [23]:
#creamos 2 arrays con números enteros que usaremos como indices
cols = np.array([0,1,2,0])
rows = np.arange(4)
print("Elegimos estos índices para filas ->", rows)
print("Elegimos estos índices para columnas ->", cols)


Elegimos estos índices para filas -> [0 1 2 3]
Elegimos estos índices para columnas -> [0 1 2 0]


In [5]:
#imprimamos los índices tomando uno de cada array, de a pares, 
for row,col in zip(rows,cols):
    print("(",row,",",col,")")

( 0 , 0 )
( 1 , 1 )
( 2 , 2 )
( 3 , 0 )


In [6]:
#entonces ahora para seleccionar un elemento de cada fila, hacemos de esta manera
print('Los valores contenidos en los índices son: ',array_a[rows, cols])

Los valores contenidos en los índices son:  [11 22 33 41]


In [7]:
#vamos a operar con los valores seleccionados
print(array_a)
array_a[rows, cols] += 1000
print(array_a)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]
[[1011   12   13]
 [  21 1022   23]
 [  31   32 1033]
 [1041   42   43]]


<br><br>
## Indexado Booleano
Indexado booleano para cambiar elementos

In [26]:
# creamos un array de 3x2
array_b = np.array([[11,12], [21, 22], [31, 32]])
print(array_b)
print("______________")
print(array_b.shape)

[[11 12]
 [21 22]
 [31 32]]
______________
(3, 2)


In [27]:
# crear un filtro es muy facil en numpy
filtro = (array_b > 15)
filtro

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [28]:
# entonces ahora podemos aplicar el filtro a nuestro array
filtrado = array_b[filtro]
print(filtrado)


[21 22 31 32]


In [11]:
# no es necesario primero crear el filtro y luego aplicarlo, podemos hacerlo al unísono
print(array_b[(array_b % 2 == 0)])


[12 22 32]


El uso principal de este tipo de filtros es el de poder modificar los valores del array que cumplan cierto criterio

In [12]:
array_b[array_b % 2 == 0] += 1000
print(array_b)

[[  11 1012]
 [  21 1022]
 [  31 1032]]


<br><br>
## Tipos de datos de los arrays numpy

In [13]:
# en este caso python se encarga de asignar el tipo de dato
ej1 = np.array([11, 12]) 
print(ej1.dtype)

int64


In [14]:
# python asigna el tipo de dato
ej2 = np.array([11.0, 12.0]) 
print(ej2.dtype) 

float64


In [15]:
# también puedo forzar el tipo de dato expresándolo de manera explícita
ej3 = np.array([11, 21], dtype=np.float64) 
print(ej3.dtype)

float64


In [16]:
# si lo necesitáramos podríamos forzar flotantes a enteros
ej4 = np.array([11.1,12.7], dtype=np.int64)
print(ej4.dtype)
print()
print(ej4)

int64

[11 12]


<br><br>
## Operaciones Aritméticas 

In [17]:
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [18]:
# resta
print(x - y)
print()
print(np.subtract(x, y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [19]:
# multiplicación 
print(x * y)
print()
print(np.multiply(x, y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [20]:
# división
print(x / y)
print()
print(np.divide(x, y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [21]:
# raíz cuadrada
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


<br><br>
## Operaciones Estadísticas Básicas 

In [22]:
# generar un array aleatorio 
arr = 10 * np.random.randn(2,5)
print(arr)

[[  6.22566282   1.71715481  -5.97700343  -2.23772028 -13.84514728]
 [ -8.83252814  -4.20879828  -6.57183308   2.08740774  12.24079493]]


In [23]:
# calcular la media (promedio) de un array
print(arr.mean())

-1.9402010174617392


In [24]:
# calcular el promedio pero en este caso, fila por fila
# importante recordar
# eje 0 = columnas
# eje 1 = filas
print(arr.mean(axis = 1))

[-2.82341067 -1.05699137]


In [25]:
# calcular el promedio pero en este caso, columna por columna
print(arr.mean(axis = 0))

[-1.30343266 -1.24582173 -6.27441825 -0.07515627 -0.80217617]


In [26]:
# creamos array de 10 elementos aleatorios 
desordenado = np.random.randn(10)
print(desordenado) 

[-0.50481956  0.84723547  0.25878339  1.02775831 -0.29779126 -1.88978477
 -2.4558705  -0.89016547 -0.33669383 -0.37651619]


In [27]:
#creamos una copia
ordenado = np.array(desordenado)

#lo ordenamos 
ordenado.sort()
print(ordenado)

[-2.4558705  -1.88978477 -0.89016547 -0.50481956 -0.37651619 -0.33669383
 -0.29779126  0.25878339  0.84723547  1.02775831]


In [28]:
#buscando elementos únicos (MUY UTIL!)
array = np.array([1,2,1,4,2,1,4,2])
print(np.unique(array))

[1 2 4]


In [29]:
# OPERACIONES DE CONJUNTO
s1 = np.array(['escritorio','silla','mesa'])
s2 = np.array(['escritorio','silla','lampara'])
print(s1)
print(s2)

['escritorio' 'silla' 'mesa']
['escritorio' 'silla' 'lampara']


In [30]:
# Intersección
print( np.intersect1d(s1, s2) ) 

['escritorio' 'silla']


In [31]:
# Union en 1d
print( np.union1d(s1, s2) )

['escritorio' 'lampara' 'mesa' 'silla']


In [32]:
# Elementos de s1 que no están en s2
print( np.setdiff1d(s1, s2) )

['mesa']


In [33]:
# que elementos de s1 están en s2
print( np.in1d(s1, s2) )

[ True  True False]


<br><br>
## Algunas operaciones frecuentes


In [29]:
#sumamos todos los elementos de un array
ex1 = np.array([[11,12],[21,22]])
print(np.sum(ex1))

66


In [30]:
# sumamos solo una columna
print(np.sum(ex1, axis=0)) 
# ¿cómo sumaríamos una fila?
print(np.sum(ex1, axis=1)) 

[32 34]
[23 43]


Reformateando un array (IMPORTANTE)

In [36]:
#creamos un array
arr = np.arange(20)
print(arr)
arr.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


(20,)

In [37]:
#cambiamos su forma
reshped_arr = arr.reshape(4,5)
print(reshped_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [38]:
#Transponer o transposicionar un array
ex1 = np.array([[11,12],[21,22]])
print(ex1)
ex1.T



[[11 12]
 [21 22]]


array([[11, 21],
       [12, 22]])

In [39]:
# WHERE ... MUY UTIL!
mat = np.random.rand(4,4)
mat

array([[0.48511215, 0.17515303, 0.11769138, 0.07259841],
       [0.51654824, 0.25815866, 0.68641084, 0.45641839],
       [0.06894296, 0.62049899, 0.45399776, 0.06725853],
       [0.47325381, 0.14609518, 0.31266844, 0.6308256 ]])

In [40]:
# le paso array condicion, valor si true, valor si false
np.where( mat > 0.5, 1000, -1)

array([[  -1,   -1,   -1,   -1],
       [1000,   -1, 1000,   -1],
       [  -1, 1000,   -1,   -1],
       [  -1,   -1,   -1, 1000]])

In [45]:
# comprobar si algun elemento del array es verdadero notar que funciona tanto con número como
# con booleanos, ya que el 0 es considerado false y todo distinto de 0 es true
arr_bools = np.array([ 0,0,0,0,0,0 ])
arr_bools.any()

False

In [49]:
# comprobar si todos los elementos del array son True
# con booleanos, ya que el 0 es considerado false y todo distinto de 0 es true
arr_bools = np.array([ 1,1,0 ])
arr_bools.all() 

False

Uniendo data sets

In [50]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)


[[43 33]
 [45 44]]

[[35 21]
 [ 2 40]]


In [51]:
#unimos "apilando" verticalmente
np.vstack((K,M))

array([[43, 33],
       [45, 44],
       [35, 21],
       [ 2, 40]])

In [52]:
#unimos "apilando" horizontamente
np.hstack((K,M))

array([[43, 33, 35, 21],
       [45, 44,  2, 40]])

In [53]:
#podemos unir concatenando
np.concatenate([K, M], axis = 0)

array([[43, 33],
       [45, 44],
       [35, 21],
       [ 2, 40]])

In [54]:
np.concatenate([K, M], axis = 1)

array([[43, 33, 35, 21],
       [45, 44,  2, 40]])

<br><br>
## Propagación

Para más detalles: 
https://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html

In [33]:
base = np.zeros((4,4))
print(base) 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [57]:
# creamos un array unidimensional
row = np.array([1, 0, 2,7])
print(row)
print(row.shape)

[1 0 2 7]
(4,)


In [60]:
y = base + row
print(y) 

[[1. 0. 2. 7.]
 [1. 0. 2. 7.]
 [1. 0. 2. 7.]
 [1. 0. 2. 7.]]


In [61]:
#repetimos lo mismo pero ahora a base le sumaremos una columna
col = np.array([[0,1,2,3]])
print(col)

[[0 1 2 3]]


In [62]:
#como vimos, necesitamos "verticalizar" esta "fila"
col = col.T
print(col)

[[0]
 [1]
 [2]
 [3]]


In [63]:
#sumemos a base
y = base + col
print(y) 

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]]


In [31]:
col = np.array([[0,1,2]]) 
col = col.T
print(col)

[[0]
 [1]
 [2]]


In [34]:
# veamos qué pasa cuando quiero hacer una operación de propagación 
y = base + col
print(y)

ValueError: operands could not be broadcast together with shapes (4,4) (3,1) 

In [67]:
arr_x = np.array([4])
print(arr_x)
print("________________")
print(base + arr_x)

[4]
________________
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]


<br><br>
# Prueba de velocidad!

In [35]:
from numpy import arange
from timeit import Timer

size    = 1000000
timeits = 1000

nd_array = arange(size)
print( "tipo de dato -> ",type(nd_array) )
print( "Forma -> ", nd_array.shape)


tipo de dato ->  <class 'numpy.ndarray'>
Forma ->  (1000000,)


In [36]:
#con la función timer podemos medir, el tiempo que lleva realizar una operación o función, 

timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")
print("Time taken by numpy ndarray: %f seconds" % (timer_numpy.timeit(timeits)))

Time taken by numpy ndarray: 0.331344 seconds


In [37]:
a_list = list(range(size))
print (type(a_list) )
print( "Forma -> ", len(a_list))

<class 'list'>
Forma ->  1000000


In [38]:
timer_list = Timer("sum(a_list)", "from __main__ import a_list")
print("Time taken by list:  %f seconds" % (timer_list.timeit(timeits)))

Time taken by list:  19.918156 seconds


<br><br>
### Grabar array a disco / recuperar array de disco

In [72]:
x = np.array([ 23.23, 24.24] )

In [73]:
 np.save('array_importante', x)


In [74]:
recuperado = np.load('array_importante.npy')
print("el array recuperado es: ", recuperado)

el array recuperado es:  [23.23 24.24]
